// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: service/v1/update_reply.proto

package v1

import (
	v1 "atypicaldev.com/conversation/notes/internal/proto/notes/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateReplyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	NoteId         string `protobuf:"bytes,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Reply          string `protobuf:"bytes,3,opt,name=reply,proto3" json:"reply,omitempty"`
}

func (x *UpdateReplyRequest) Reset() {
	*x = UpdateReplyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_v1_update_reply_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReplyRequest) ProtoMessage() {}

func (x *UpdateReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_update_reply_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReplyRequest.ProtoReflect.Descriptor instead.
func (*UpdateReplyRequest) Descriptor() ([]byte, []int) {
	return file_service_v1_update_reply_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateReplyRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *UpdateReplyRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *UpdateReplyRequest) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type UpdateReplyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Note *v1.Note `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
}

func (x *UpdateReplyResponse) Reset() {
	*x = UpdateReplyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_v1_update_reply_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReplyResponse) ProtoMessage() {}

func (x *UpdateReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_update_reply_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReplyResponse.ProtoReflect.Descriptor instead.
func (*UpdateReplyResponse) Descriptor() ([]byte, []int) {
	return file_service_v1_update_reply_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateReplyResponse) GetNote() *v1.Note {
	if x != nil {
		return x.Note
	}
	return nil
}

var File_service_v1_update_reply_proto protoreflect.FileDescriptor

var file_service_v1_update_reply_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x13, 0x6e, 0x6f, 0x74,
	0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x6c, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72,
	0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6e, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6c,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x39,
	0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4e,
	0x6f, 0x74, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x42, 0x3e, 0x5a, 0x3c, 0x61, 0x74, 0x79,
	0x70, 0x69, 0x63, 0x61, 0x6c, 0x64, 0x65, 0x76, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_service_v1_update_reply_proto_rawDescOnce sync.Once
	file_service_v1_update_reply_proto_rawDescData = file_service_v1_update_reply_proto_rawDesc
)

func file_service_v1_update_reply_proto_rawDescGZIP() []byte {
	file_service_v1_update_reply_proto_rawDescOnce.Do(func() {
		file_service_v1_update_reply_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_v1_update_reply_proto_rawDescData)
	})
	return file_service_v1_update_reply_proto_rawDescData
}

var file_service_v1_update_reply_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_v1_update_reply_proto_goTypes = []interface{}{
	(*UpdateReplyRequest)(nil),  // 0: service.v1.UpdateReplyRequest
	(*UpdateReplyResponse)(nil), // 1: service.v1.UpdateReplyResponse
	(*v1.Note)(nil),             // 2: notes.v1.Note
}
var file_service_v1_update_reply_proto_depIdxs = []int32{
	2, // 0: service.v1.UpdateReplyResponse.note:type_name -> notes.v1.Note
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_v1_update_reply_proto_init() }
func file_service_v1_update_reply_proto_init() {
	if File_service_v1_update_reply_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_v1_update_reply_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReplyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_v1_update_reply_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReplyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_v1_update_reply_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_v1_update_reply_proto_goTypes,
		DependencyIndexes: file_service_v1_update_reply_proto_depIdxs,
		MessageInfos:      file_service_v1_update_reply_proto_msgTypes,
	}.Build()
	File_service_v1_update_reply_proto = out.File
	file_service_v1_update_reply_proto_rawDesc = nil
	file_service_v1_update_reply_proto_goTypes = nil
	file_service_v1_update_reply_proto_depIdxs = nil
}
